DROP TABLE users IF EXISTS;
DROP TABLE questions IF EXISTS;
DROP TABLE answers IF EXISTS;
DROP TABLE answer_options IF EXISTS;

CREATE TABLE users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(30),
    last_name       VARCHAR(30),
    email           VARCHAR(50),
    password        VARCHAR(255),
    phone_number    VARCHAR(20)
);

CREATE INDEX users_last_name ON users (last_name);

CREATE TABLE questions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question        VARCHAR(255),
    answer_type     VARCHAR(20),
    from_user_id    INTEGER,
    to_user_id      INTEGER
);

ALTER TABLE questions ADD CONSTRAINT fk_question_users_from FOREIGN KEY (from_user_id) REFERENCES users (id);
ALTER TABLE questions ADD CONSTRAINT fk_question_users_to FOREIGN KEY (to_user_id) REFERENCES users (id) ON DELETE SET NULL;

CREATE TABLE answers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer      VARCHAR(255),
    question_id INTEGER
);

ALTER TABLE answers ADD CONSTRAINT fk_answers_questions FOREIGN KEY (question_id) REFERENCES questions (id);

CREATE TABLE answer_options (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option      VARCHAR(255),
    question_id INTEGER
);

ALTER TABLE answer_options ADD CONSTRAINT fk_options_questions FOREIGN KEY (question_id) REFERENCES questions (id);